   
target ‘R360SmartEyes’ do

    pod 'TesseractOCRiOS', '~> 4.0.0'
    pod 'LLSimpleCamera', '~> 5.0.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'CardIO', '5.3.2'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Base64', '~> 1.1.2'
    pod 'JSONKit', '1.4'
end
